---
- name: Collect set of facts in PowerScale
  hosts: localhost
  connection: local

  tasks:
    - name: Get attributes, access_zones and nodes of the PowerScale cluster
      dellemc.powerscale.info:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        gather_subset:
          - attributes
          - access_zones
          - nodes
